name: Build Android APK AGN

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Generate Complete App & Build
      run: |
        mkdir -p ../temp_save
        cp -r lib ../temp_save/ 2>/dev/null || true
        cp pubspec.yaml ../temp_save/ 2>/dev/null || true
        cp android/app/src/main/AndroidManifest.xml ../temp_save/ 2>/dev/null || true

        rm -rf * .github
        flutter create --org com.aliagunanusantara .

        cp -r ../temp_save/lib ./ 2>/dev/null || true
        cp ../temp_save/AndroidManifest.xml android/app/src/main/ 2>/dev/null || true
        
        flutter pub add mobile_scanner geolocator

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patroli-AGN-Release-APK
        path: build/app/outputs/flutter-apk/app-release.apk
