name: Build Android APK AGN

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Repair Android Structure & Build
      run: |
        # Simpan file penting kita
        mkdir -p temp_backup
        cp -r lib temp_backup/
        cp pubspec.yaml temp_backup/
        
        # Buat proyek baru
        flutter create --org com.aliaguna --project-name patroli_agn temp_app
        
        # Bersihkan folder lib bawaan lalu timpa dengan milik kita
        rm -rf temp_app/lib
        cp -r temp_backup/lib temp_app/lib
        cp temp_backup/pubspec.yaml temp_app/pubspec.yaml
        
        # Build Debug APK
        cd temp_app
        flutter pub get
        flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patroli-AGN-Debug-APK
        path: temp_app/build/app/outputs/flutter-apk/app-debug.apk
